apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.web.superuser.username | quote | b64enc}}
  password: {{ .Values.web.superuser.password | quote | b64enc }}